Add log collection on failuer (artifacts), improve error detection

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -43,6 +43,12 @@ build:
 
 image-test:
   stage: test
+  artifacts:
+    name: "${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}"
+    when: on_failure
+    expire_in: 1 week
+    paths:
+      - logs/
   script:
     - echo "Pulling docker container ${REGISTRY_IMAGE} ..."
     - docker pull ${REGISTRY_IMAGE}
@@ -102,18 +108,24 @@ image-test:
         --env="GOOGLE_ANALYTICS_ID=UA-123-ab"
         --env="GITALY_ENABLED=true"
         --env="VERBOSE=true"
+        --volume ./logs:/var/log/gitlab
         ${REGISTRY_IMAGE}
     - echo "Waiting for containers to start and settle, 90 seconds ..."
     - sleep 90
     - echo "Wait for gitlab to recompile assets ..."
     - while [[ $(docker logs gitlab-test | tail -n 1 | grep -c "Recompiling assets") != 0 ]]; do sleep 30; echo "Still waiting ..."; done
+    - sleep 30
+    - docker logs gitlab-test > logs/docker-logs-gitlab.log 2>&1
+    - docker logs gitlab-postgresql > logs/docker-logs-postgresql.log 2>&1
+    - docker logs gitlab-redis > logs/docker-logs-redis.log 2>&1
     - docker logs gitlab-test
     - export RC=0
-    - if [[ $(docker logs gitlab-test | grep -i "error\|fail\|exit" | grep -c -i -v info) != 0 ]]; then export RC=1; fi
+    - if [[ $(docker logs gitlab-test | grep -i "error\|fail\|exit\|fatal" | grep -c -i -v info) != 0 ]]; then
+        export RC=1; docker logs gitlab-test | grep -i "error\|fail\|exit\|fatal" | grep -i -v info; fi
     - echo "Stopping and removing containers ..."
     - docker stop gitlab-test gitlab-redis gitlab-postgresql
     - docker rm -f gitlab-test gitlab-redis gitlab-postgresql
-    - if [[ $RC != 0 ]]; then docker logs gitlab-test | grep -i "error\|fail\|exit" | grep -i -v info; exit $RC; fi
+    - if [[ $RC != 0 ]]; then exit $RC; fi
   except:
     - latest
 
